# Generated by Django 3.2.8 on 2021-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documents_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='documents',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
