# Generated by Django 3.2.8 on 2021-11-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_digitalcert'),
    ]

    operations = [
        migrations.CreateModel(
            name='selfSignedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_url', models.URLField()),
                ('originalDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents')),
            ],
        ),
    ]
