# Generated by Django 3.2.8 on 2021-11-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_selfsigneddoc_originaldoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsigneddoc',
            name='originalDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_url', to='documents.documents'),
        ),
    ]
