# Generated by Django 3.2.8 on 2021-11-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_signigreq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignigReq',
        ),
    ]
