# Generated by Django 3.2.8 on 2021-12-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20211201_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signigreq',
            name='signed_url',
            field=models.URLField(),
        ),
    ]
