# Generated by Django 3.2.8 on 2021-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_signigreq_signed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signigreq',
            name='signed_url',
            field=models.URLField(blank=True),
        ),
    ]
