# Generated by Django 3.2.8 on 2021-12-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_signigreq_signed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signigreq',
            name='signed_url',
        ),
        migrations.AddField(
            model_name='reqsigndoc',
            name='signed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reqsigndoc',
            name='status',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='signigreq',
            name='status',
            field=models.CharField(default='', max_length=225),
        ),
    ]
