# Generated by Django 3.2.8 on 2021-12-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20211202_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfsigneddocuments',
            name='ori_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
