# Generated by Django 3.2.8 on 2021-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_selfsigneddocuments_ori_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfsigneddocuments',
            name='ori_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
