# Generated by Django 3.2.8 on 2021-12-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_alter_reqsigndoc_signed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=225)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents')),
            ],
        ),
    ]
